# Generated by Django 3.2.23 on 2023-12-24 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
