# Generated by Django 3.2.23 on 2023-12-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20231226_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
