# Generated by Django 3.2.23 on 2023-12-26 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_account_subscribed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='subscribed',
        ),
    ]
