# Generated by Django 3.2.23 on 2023-12-26 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20231225_1312'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
