# Generated by Django 3.2.23 on 2023-12-26 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0008_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='account',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='account.account'),
            preserve_default=False,
        ),
    ]
