# Generated by Django 3.2.23 on 2023-12-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_subscribe_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
