# Generated by Django 3.2.23 on 2023-12-27 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_acitve',
            field=models.BooleanField(default=True),
        ),
    ]
